WITH TEMP(PNLNAME) AS (SELECT A.PNLNAME FROM PSPNLGROUP A WHERE A.PNLGRPNAME = 'BUS_UNIT_TBL_GL'
UNION ALL
SELECT B.SUBPNLNAME FROM PSPNLFIELD B,TEMP WHERE TEMP.PNLNAME = B.PNLNAME)
SELECT DISTINCT C.RECNAME FROM TEMP,PSPNLFIELD C,PSRECDEFN D WHERE TEMP.PNLNAME = C.PNLNAME
AND C.RECNAME = D.RECNAME AND D.RECTYPE = 0

WITH TEMP(PNLNAME) AS (SELECT A.PNLNAME FROM PSPNLGROUP A WHERE A.PNLGRPNAME = 'ALLOC_GROUP'
UNION ALL
SELECT B.SUBPNLNAME FROM PSPNLFIELD B,TEMP WHERE TEMP.PNLNAME = B.PNLNAME)
SELECT DISTINCT C.RECNAME FROM TEMP,PSPNLFIELD C WHERE TEMP.PNLNAME = C.PNLNAME
